// ======================
// SMART KEYBOARD SYSTEM
// ======================

function closeKeyboard(){
    if(document.activeElement){
        document.activeElement.blur();
    }
}

document.addEventListener("keydown", function(e){

    const active = document.activeElement;

    const amountEl   = document.getElementById("amount");
    const durationEl = document.getElementById("duration");
    const monthlyEl  = document.getElementById("monthly");
    const unitEl     = document.getElementById("unit");

    const isInput = active && (
        active.tagName === "INPUT" ||
        active.tagName === "TEXTAREA"
    );

    const page = window.location.pathname;

    // ======================
    // ESC → BACK
    // ======================
    if(e.key === "Escape"){
        goBack();
        return;
    }

    // ======================
    // DELETE → RESET
    // ======================
    if(e.key === "Delete"){

        if(page.includes("ridc")) resetRIDC();
        else if(page.includes("midr")) resetMIDR();
        else if(page.includes("rd")) resetRD();

        return;
    }

    // ======================
    // NUMBER → AUTO FOCUS FIRST INPUT
    // ======================
    if(!isInput && /^[0-9]$/.test(e.key)){

        const firstInput = amountEl || monthlyEl;

        if(firstInput){
            firstInput.focus();
            firstInput.value = e.key;
            e.preventDefault();
        }
        return;
    }

    // ======================
    // ENTER FLOW
    // ======================
    if(e.key === "Enter"){
        e.preventDefault();

        // 1️⃣ Amount → Duration
        if(active === amountEl && durationEl){
            durationEl.focus();
            durationEl.select();
            return;
        }

        // 2️⃣ RD Monthly → Duration
        if(active === monthlyEl && durationEl){
            durationEl.focus();
            durationEl.select();
            return;
        }

        // ❌ Ignore dropdown completely
        if(active === unitEl){
            return;
        }

        // 3️⃣ Duration → Calculate
        if(active === durationEl){

            if(page.includes("ridc")) calculateRIDC();
            else if(page.includes("midr")) calculateMIDR();
            else if(page.includes("rd")) calculateRD();
closeKeyboard();

            return;
        }

        // 4️⃣ Fallback (safety)
        if(page.includes("ridc")) calculateRIDC();
        else if(page.includes("midr")) calculateMIDR();
        else if(page.includes("rd")) calculateRD();
    }

});

// ======================
// COPY PROTECTION
// ======================

// Disable right click
document.addEventListener("contextmenu", e => e.preventDefault());

// Disable text selection
document.addEventListener("selectstart", e => e.preventDefault());

// Disable copy
document.addEventListener("copy", e => e.preventDefault());

// Disable key shortcuts


    // Ctrl+C / Ctrl+U / Ctrl+S
    if(e.ctrlKey && ["c","u","s"].includes(e.key.toLowerCase())){
        e.preventDefault();
    }

    // F12 (Dev tools)
    if(e.key === "F12"){
        e.preventDefault();
    }

});


function exportPDF(){

    if(!shareData){
        alert("Please calculate first");
        return;
    }

    if(typeof pdfMake === "undefined"){
        alert("PDF engine not loaded");
        return;
    }

    // ===== DETECT TYPE =====
    let type = "Deposit";

    const titleText = document.title.toLowerCase();

    if(titleText.includes("ridc")) type = "RIDC";
    else if(titleText.includes("midr")) type = "MIDR";
    else if(titleText.includes("rd")) type = "RD";

    // ===== PARSE DATA =====
    const rows = shareData
        .split("\n")
        .filter(l => l.trim())
        .map(line => {
            let parts = line.replace("•","").split(":");
            return [
                { text: parts[0]?.trim(), style:'label' },
                { text: parts.slice(1).join(":").trim(), style:'value' }
            ];
        });

    // ===== PDF =====
    const docDefinition = {

        pageMargins: [25, 25, 25, 25],

        content: [

            {
                text: `${type} Summary`,
                style: "header"
            },

            {
                margin: [0,10],
                table: {
                    widths: ['*','auto'],
                    body: rows
                },
                layout: {
                    fillColor: () => '#FFFFFF',
                    hLineColor: () => '#E0E0E0',
                    vLineWidth: () => 0,
                    paddingTop: () => 8,
                    paddingBottom: () => 8,
                    paddingLeft: () => 10,
                    paddingRight: () => 10
                }
            },

            {
                text: "Generated by Bank Calculator",
                alignment: "center",
                style: "footer"
            }

        ],

        styles: {

            header: {
                fontSize: 20,
                bold: true,
                color: '#6750A4',
                margin: [0,0,0,10]
            },

            label: {
                fontSize: 15,
                color: '#444'
            },

            value: {
                fontSize: 15,
                bold: true,
                alignment: 'right'
            },

            footer: {
                fontSize: 10,
                color: 'gray',
                margin: [0,20,0,0]
            }

        }
    };

    pdfMake.createPdf(docDefinition).download(`${type}_Result.pdf`);
}

// ==== DEFAULT =====

let senior = "no";
let panStatus = "yes";
let staff = "no";
let payoutType = "monthly";

// ======================
// UTIL
// ======================

function getDays(v,u){
    return u==="days"?v:u==="months"?v*(365/12):v*365;
}
function formatINR(val){
    return new Intl.NumberFormat('en-IN', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(Number(val));
}
function getMaturityDate(value, unit){
    let d = new Date();
    if(unit==="days") d.setDate(d.getDate()+Number(value));
    if(unit==="months") d.setMonth(d.getMonth()+Number(value));
    if(unit==="years") d.setFullYear(d.getFullYear()+Number(value));

    return `${d.getDate()} ${d.toLocaleString("en-GB",{month:"long"})}, ${d.getFullYear()}`;
}

// ======================
// BACK BUTTON
// ======================

function goBack(){
    if(window.history.length > 1){
        window.history.back();
    } else {
        window.location.href = "index.html";
    }
}

// ======================
// TDS
// ======================

function calculateTDS(interest){
    let threshold = (senior==="yes") ? 100000 : 50000;

    if(interest < threshold){
        return {applicable:false, tds:0, net:interest};
    }

    let rate = (panStatus==="no") ? 0.20 : 0.10;
    let tds = interest * rate;

    return {
        applicable:true,
        tds:tds,
        net:interest - tds,
        rate:rate*100
    };
}

// ======================
// RIDC
// ======================

function calculateRIDC(){
    let P = +amount.value;
    let D = +duration.value;
    if(!P) return showError("Enter deposit amount");
    if(!D) return showError("Enter duration");
    let unitVal = document.getElementById("unit").value;
    let days = getDays(D, unit.value);
    let r = getRate(days);
if(!r){
    return showError("Invalid duration");
}
    let maturity, interest;
    if(days < 180){
        interest = (P*r*days)/(365*100);
        maturity = P + interest;
    } else {
        let q = Math.floor(days/91);
        maturity = P * Math.pow(1+r/100/4,q);
        let rem = days - (q*91);
        maturity += (maturity*r*rem)/(365*100);
        interest = maturity - P;
    }
    let tdsData = calculateTDS(interest);
    let unitText = unitVal;

shareData = `
• Deposit Amount: ₹${formatINR(P)}
• Rate of Interest: ${r}%
• Duration: ${D} ${unitText}

• Maturity: ${getMaturityDate(D, unitVal)}
${tdsData.applicable ? `
• Maturity (Without TDS): ₹${formatINR(maturity)}
• Total Interest: + ₹${formatINR(interest)}
• TDS (${tdsData.rate}%): - ₹${formatINR(tdsData.tds)}
• Net Interest: + ₹${formatINR(tdsData.net)}
• Maturity (With TDS): ₹${formatINR(maturity - tdsData.tds)}
` : `
• Maturity Amount: ₹${formatINR(maturity)}
• Total Interest: + ₹${formatINR(interest)}
`}
`;

result.innerHTML = `
<div class="maturity-row">

<div class="maturity-chip">
<strong>Maturity</strong> :‎ ‎ ${getMaturityDate(D, unitVal)}
</div>

<div class="share-btn" onclick="exportPDF()">
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 2H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-8.5 7.5c0 .83-.67 1.5-1.5 1.5H9v2H7.5V7H10c.83 0 1.5.67 1.5 1.5v1zm5 2c0 .83-.67 1.5-1.5 1.5h-2.5V7H15c.83 0 1.5.67 1.5 1.5v3zm4-3H19v1h1.5V11H19v2h-1.5V7h3v1.5zM9 9.5h1v-1H9v1zM4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm10 5.5h1v-3h-1v3z"/></svg>
</div>

</div>

${tdsData.applicable ? `
<div class="result-line">
<span>Maturity (Without TDS)</span>
<span class="strong gain">₹${formatINR(maturity)}</span>
</div>` : `
<div class="result-line">
<span>Maturity Amount</span>
<span class="strong gain">₹${formatINR(maturity)}</span>
</div>`}

<div class="result-line">
<span>Total Interest</span>
<span class="gain">+ ₹${formatINR(interest)}</span>
</div>

${tdsData.applicable ? `
<div class="result-line loss strong">
<span class="tds-label">TDS (${tdsData.rate}%)</span>
<span class="loss">- ₹${formatINR(tdsData.tds)}</span>
</div>

<div class="result-line">
<span>Net Interest</span>
<span class="gain">+ ₹${formatINR(tdsData.net)}</span>
</div>

<div class="result-line">
<span>Maturity (With TDS)</span>
<span class="strong gain">₹${formatINR(maturity - tdsData.tds)}</span>
</div>` : ""}
`;
scrollToResult();
}

// ======================
// MIDR
// ======================

function calculateMIDR(){
    let P = +amount.value;
    let D = +duration.value;
    if(!P) return showError("Enter deposit amount");
    if(!D) return showError("Enter duration");
    let unitVal = document.getElementById("unit").value;
    let days = getDays(D, unit.value);
    let r = getRate(days);
if(!r){
    return showError("Invalid duration");
}

    let interest = (P*r*days)/(365*100);
    let tdsData = calculateTDS(interest);
    let cycles = Math.max(1, Math.floor(days/(payoutType==="monthly"?30:91)));
let unitText = unitVal;

shareData = `
• Deposit Amount: ₹${formatINR(P)}
• Rate of Interest: ${r}%
• Duration: ${D} ${unitText}

• Maturity: ${getMaturityDate(D, unitVal)}

${tdsData.applicable ? `
• Payout (Without TDS): ₹${formatINR(interest/cycles)} ${payoutType}
• Maturity Amount: ₹${formatINR(P)}
• Total Interest: + ₹${formatINR(interest)}
• TDS (${tdsData.rate}%): - ₹${formatINR(tdsData.tds)}
• Net Interest: + ₹${formatINR(tdsData.net)}
• Payout (With TDS): ₹${formatINR(tdsData.net/cycles)} ${payoutType}
` : `
• Payout: ₹${formatINR(interest/cycles)} ${payoutType}
• Maturity Amount: ₹${formatINR(P)}
• Total Interest: + ₹${formatINR(interest)}
`}
`;

    result.innerHTML = `
<div class="maturity-row">

<div class="maturity-chip">
<strong>Maturity</strong> :‎ ‎ ${getMaturityDate(D, unitVal)}
</div>

<div class="share-btn" onclick="exportPDF()">
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 2H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-8.5 7.5c0 .83-.67 1.5-1.5 1.5H9v2H7.5V7H10c.83 0 1.5.67 1.5 1.5v1zm5 2c0 .83-.67 1.5-1.5 1.5h-2.5V7H15c.83 0 1.5.67 1.5 1.5v3zm4-3H19v1h1.5V11H19v2h-1.5V7h3v1.5zM9 9.5h1v-1H9v1zM4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm10 5.5h1v-3h-1v3z"/></svg>
</div>

</div>

${tdsData.applicable ? `
<div class="result-line">
<span>Payout (Without TDS)</span>
<span class="gain strong">₹${formatINR(interest/cycles)}</span>
</div>
` : `
<div class="result-line">
<span>Payout</span>
<span class="gain strong">₹${formatINR(interest/cycles)}</span>
</div>
`}

<div class="result-line">
<span>Maturity Amount</span>
<span>₹${formatINR(P)}</span>
</div>

<div class="result-line">
<span>Total Interest</span>
<span class="gain">+ ₹${formatINR(interest)}</span>
</div>

${tdsData.applicable ? `
<div class="result-line loss strong">
<span class="tds-label">TDS (${tdsData.rate}%)</span>
<span class="loss">- ₹${formatINR(tdsData.tds)}</span>
</div>

<div class="result-line">
<span>Net Interest</span>
<span class="gain">+ ₹${formatINR(tdsData.net)}</span>
</div>

<div class="result-line">
<span>Payout (With TDS)</span>
<span class="gain strong">₹${formatINR(tdsData.net/cycles)}</span>
</div>` : `
`}
`;
scrollToResult();
}

// ======================
// RD
// ======================

function calculateRD(){
    let P = +monthly.value;
    let D = +duration.value;
    if(!P) return showError("Enter monthly deposit");
    if(!D) return showError("Enter duration");
    let unitVal = document.getElementById("unit").value;
    let months = unit.value==="months"?D:Math.floor(D/30);
    let days = getDays(D, unit.value);
    let r = getRate(days);
if(!r){
    return showError("Invalid duration");
}
    let maturity=0;
    for(let i=0;i<months;i++){
        maturity += P*Math.pow(1+r/100/4,(months-i)/3);
    }
    let interest = maturity - (P*months);
    let tdsData = calculateTDS(interest);
let unitText = unitVal;

shareData = `
• Monthly Deposit: ₹${formatINR(P)}
• Rate of Interest: ${r}%
• Duration: ${D} ${unitText}

• Maturity: ${getMaturityDate(D, unitVal)}

${tdsData.applicable ? `
• Total Deposit: ₹${formatINR(P*months)}
• Maturity (Without TDS): ₹${formatINR(maturity)}
• Total Interest: + ₹${formatINR(interest)}
• TDS (${tdsData.rate}%): - ₹${formatINR(tdsData.tds)}
• Net Interest: + ₹${formatINR(tdsData.net)}
• Maturity (With TDS): ₹${formatINR(maturity - tdsData.tds)}
` : `
• Total Deposit: ₹${formatINR(P*months)}
• Maturity Amount: ₹${formatINR(maturity)}
• Total Interest: + ₹${formatINR(interest)}
`}
`;
    result.innerHTML = `
<div class="maturity-row">

<div class="maturity-chip">
<strong>Maturity</strong> :‎ ‎ ${getMaturityDate(D, unitVal)}
</div>

<div class="share-btn" onclick="exportPDF()">
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 2H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-8.5 7.5c0 .83-.67 1.5-1.5 1.5H9v2H7.5V7H10c.83 0 1.5.67 1.5 1.5v1zm5 2c0 .83-.67 1.5-1.5 1.5h-2.5V7H15c.83 0 1.5.67 1.5 1.5v3zm4-3H19v1h1.5V11H19v2h-1.5V7h3v1.5zM9 9.5h1v-1H9v1zM4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm10 5.5h1v-3h-1v3z"/></svg>
</div>

</div>

<div class="result-line">
<span>Total Deposit</span>
<span>₹${formatINR(P*months)}</span>
</div>

${tdsData.applicable ? `
<div class="result-line">
<span>Maturity (Without TDS)</span>
<span class="gain strong">₹${formatINR(maturity)}</span>
</div>` : `
<div class="result-line">
<span>Maturity Amount</span>
<span class="gain strong">₹${formatINR(maturity)}</span>
</div>`}

<div class="result-line">
<span>Total Interest</span>
<span class="gain">+ ₹${formatINR(interest)}</span>
</div>

${tdsData.applicable ? `
<div class="result-line strong loss">
<span class="tds-label">TDS (${tdsData.rate}%)</span>
<span class="loss">- ₹${formatINR(tdsData.tds)}</span>
</div>

<div class="result-line">
<span>Net Interest</span>
<span class="gain">+ ₹${formatINR(tdsData.net)}</span>
</div>

<div class="result-line">
<span>Maturity (With TDS)</span>
<span class="gain strong">₹${formatINR(maturity - tdsData.tds)}</span>
</div>` : ""}
`;
scrollToResult();
}

// ======================
// RESET
// ======================

function resetRIDC(){
    amount.value="";
    duration.value="";
    result.innerHTML = `
<div class="result-line"><span>Maturity Amount</span><span>--</span></div>
<div class="result-line"><span>Interest Earned</span><span>--</span></div>`;
}

function resetMIDR(){
    amount.value="";
    duration.value="";
    result.innerHTML = `
<div class="result-line"><span>Payout</span><span>--</span></div>
<div class="result-line"><span>Maturity Amount</span><span>--</span></div>
<div class="result-line"><span>Total Interest</span><span>--</span></div>`;
}

function resetRD(){
    monthly.value="";
    duration.value="";
    result.innerHTML = `
<div class="result-line"><span>Total Deposit</span><span>--</span></div>
<div class="result-line"><span>Maturity Amount</span><span>--</span></div>
<div class="result-line"><span>Total Interest</span><span>--</span></div>`;
}

// ======================
// SNACKBAR ERROR + AUTO FOCUS
// ======================

function showError(msg){

    let bar = document.getElementById("snackbar");

    // Show message
    if(!bar){
        alert(msg);
    } else {
        bar.innerText = msg;
        bar.classList.add("show");
        setTimeout(()=>bar.classList.remove("show"),2500);
    }

    // ======================
    // AUTO FOCUS LOGIC
    // ======================

    const amountEl   = document.getElementById("amount");
    const durationEl = document.getElementById("duration");
    const monthlyEl  = document.getElementById("monthly");

    const m = msg.toLowerCase();

    // Deposit amount (RIDC / MIDR)
    if(m.includes("deposit amount") && amountEl){
        amountEl.focus();
        amountEl.select();
        return;
    }

    // Monthly deposit (RD)
    if(m.includes("monthly") && monthlyEl){
        monthlyEl.focus();
        monthlyEl.select();
        return;
    }

    // Duration
    if(m.includes("duration") && durationEl){
        durationEl.focus();
        durationEl.select();
        return;
    }
}

// ======================
// RESET SCROLL ON PAGE LOAD
// ======================
window.addEventListener("pageshow", ()=>window.scrollTo(0,0));

// ======================
// TOGGLES
// ======================

// SENIOR
function setSenior(val){
    senior = val;

    seniorNo.classList.toggle("active", val==="no");
    seniorYes.classList.toggle("active", val==="yes");

    autoRate();
}

// STAFF
function setStaff(val){
    staff = val;

    staffNo.classList.toggle("active", val==="no");
    staffYes.classList.toggle("active", val==="yes");

    autoRate();
}

// PAN
function setPAN(val){
    panStatus = val;

    panYes.classList.toggle("active", val==="yes");
    panNo.classList.toggle("active", val==="no");
}

// PAYOUT (MIDR)
function setPayout(val){
    payoutType = val;

    monthly.classList.toggle("active", val==="monthly");
    quarterly.classList.toggle("active", val==="quarterly");
}

// ======================
// MODAL MENU 
// ======================

function openUnit(){
    const modal = document.getElementById("unitModal");
    if(modal) modal.style.display = "flex";
}

function closeUnit(){
    const modal = document.getElementById("unitModal");
    if(modal) modal.style.display = "none";
}

function selectUnit(val, text, el){

    const unitEl = document.getElementById("unit");
    const unitText = document.getElementById("unitText");

    if(unitEl) unitEl.value = val;
    if(unitText) unitText.innerText = text;

    document.querySelectorAll(".option").forEach(o=>o.classList.remove("active"));
    el.classList.add("active");

    closeUnit();
    autoRate();
}

// CLOSE ON OUTSIDE CLICK

window.addEventListener("click", function(e){
    const modal = document.getElementById("unitModal");
    if(e.target === modal){
        closeUnit();
    }
});


// ======================
// AUTO SCROLL TO RESULT
// ======================

function scrollToResult(){
// ❌ Disable on desktop
    if(window.innerWidth >= 768) return;
    const el = document.getElementById("result");
    if(!el) return;

    setTimeout(()=>{
        el.scrollIntoView({
            behavior: "smooth",
            block: "start"
        });
    }, 50);
}
